import * as v from "valibot";

export const AnnListSchema = v.object({
  retcode: v.number(),
  message: v.string(),
  data: v.object({
    list: v.array(
      v.object({
        list: v.array(
          v.object({
            ann_id: v.number(),
            title: v.string(),
            subtitle: v.string(),
            banner: v.string(),
            content: v.string(),
            type_label: v.string(),
            tag_label: v.string(),
            tag_icon: v.string(),
            login_alert: v.number(),
            lang: v.string(),
            start_time: v.string(),
            end_time: v.string(),
            type: v.number(),
            remind: v.number(),
            alert: v.number(),
            tag_start_time: v.string(),
            tag_end_time: v.string(),
            remind_ver: v.number(),
            has_content: v.boolean(),
            extra_remind: v.number(),
            tag_icon_hover: v.string(),
            logout_remind: v.number(),
            logout_remind_ver: v.number(),
            country: v.string(),
            need_remind_text: v.number(),
            remind_text: v.string(),
            weak_remind: v.number(),
            remind_consumption_type: v.number(),
          }),
        ),
        type_id: v.number(),
        type_label: v.string(),
      }),
    ),
    total: v.number(),
    type_list: v.array(
      v.object({
        id: v.number(),
        name: v.string(),
        mi18n_name: v.string(),
      }),
    ),
    alert: v.boolean(),
    alert_id: v.number(),
    timezone: v.number(),
    t: v.string(),
    pic_list: v.array(v.unknown()),
    pic_total: v.number(),
    pic_type_list: v.array(v.unknown()),
    pic_alert: v.boolean(),
    pic_alert_id: v.number(),
    static_sign: v.string(),
    banner: v.string(),
    calendar_type: v.object({
      mi18n_name: v.string(),
      enabled: v.boolean(),
      remind: v.boolean(),
    }),
    use_webp: v.string(),
  }),
});
