/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementRouteImport } from './routes/announcement'
import { Route as AnnouncementBh3RouteImport } from './routes/announcement.bh3'
import { Route as AnnouncementHk4eRouteImport } from './routes/announcement.hk4e'
import { Route as AnnouncementHkrpgRouteImport } from './routes/announcement.hkrpg'
import { Route as AnnouncementNapRouteImport } from './routes/announcement.nap'
import { Route as ApiAnnouncementBh3RouteImport } from './routes/api.announcement.bh3'
import { Route as ApiAnnouncementHk4eRouteImport } from './routes/api.announcement.hk4e'
import { Route as ApiAnnouncementHkrpgRouteImport } from './routes/api.announcement.hkrpg'
import { Route as ApiAnnouncementNapRouteImport } from './routes/api.announcement.nap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementRoute = AnnouncementRouteImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementBh3Route = AnnouncementBh3RouteImport.update({
  id: '/bh3',
  path: '/bh3',
  getParentRoute: () => AnnouncementRoute,
} as any)
const AnnouncementHk4eRoute = AnnouncementHk4eRouteImport.update({
  id: '/hk4e',
  path: '/hk4e',
  getParentRoute: () => AnnouncementRoute,
} as any)
const AnnouncementHkrpgRoute = AnnouncementHkrpgRouteImport.update({
  id: '/hkrpg',
  path: '/hkrpg',
  getParentRoute: () => AnnouncementRoute,
} as any)
const AnnouncementNapRoute = AnnouncementNapRouteImport.update({
  id: '/nap',
  path: '/nap',
  getParentRoute: () => AnnouncementRoute,
} as any)
const ApiAnnouncementBh3Route = ApiAnnouncementBh3RouteImport.update({
  id: '/api/announcement/bh3',
  path: '/api/announcement/bh3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementHk4eRoute = ApiAnnouncementHk4eRouteImport.update({
  id: '/api/announcement/hk4e',
  path: '/api/announcement/hk4e',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementHkrpgRoute = ApiAnnouncementHkrpgRouteImport.update({
  id: '/api/announcement/hkrpg',
  path: '/api/announcement/hkrpg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementNapRoute = ApiAnnouncementNapRouteImport.update({
  id: '/api/announcement/nap',
  path: '/api/announcement/nap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteWithChildren
  '/announcement/bh3': typeof AnnouncementBh3Route
  '/announcement/hk4e': typeof AnnouncementHk4eRoute
  '/announcement/hkrpg': typeof AnnouncementHkrpgRoute
  '/announcement/nap': typeof AnnouncementNapRoute
  '/api/announcement/bh3': typeof ApiAnnouncementBh3Route
  '/api/announcement/hk4e': typeof ApiAnnouncementHk4eRoute
  '/api/announcement/hkrpg': typeof ApiAnnouncementHkrpgRoute
  '/api/announcement/nap': typeof ApiAnnouncementNapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteWithChildren
  '/announcement/bh3': typeof AnnouncementBh3Route
  '/announcement/hk4e': typeof AnnouncementHk4eRoute
  '/announcement/hkrpg': typeof AnnouncementHkrpgRoute
  '/announcement/nap': typeof AnnouncementNapRoute
  '/api/announcement/bh3': typeof ApiAnnouncementBh3Route
  '/api/announcement/hk4e': typeof ApiAnnouncementHk4eRoute
  '/api/announcement/hkrpg': typeof ApiAnnouncementHkrpgRoute
  '/api/announcement/nap': typeof ApiAnnouncementNapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteWithChildren
  '/announcement/bh3': typeof AnnouncementBh3Route
  '/announcement/hk4e': typeof AnnouncementHk4eRoute
  '/announcement/hkrpg': typeof AnnouncementHkrpgRoute
  '/announcement/nap': typeof AnnouncementNapRoute
  '/api/announcement/bh3': typeof ApiAnnouncementBh3Route
  '/api/announcement/hk4e': typeof ApiAnnouncementHk4eRoute
  '/api/announcement/hkrpg': typeof ApiAnnouncementHkrpgRoute
  '/api/announcement/nap': typeof ApiAnnouncementNapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcement'
    | '/announcement/bh3'
    | '/announcement/hk4e'
    | '/announcement/hkrpg'
    | '/announcement/nap'
    | '/api/announcement/bh3'
    | '/api/announcement/hk4e'
    | '/api/announcement/hkrpg'
    | '/api/announcement/nap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcement'
    | '/announcement/bh3'
    | '/announcement/hk4e'
    | '/announcement/hkrpg'
    | '/announcement/nap'
    | '/api/announcement/bh3'
    | '/api/announcement/hk4e'
    | '/api/announcement/hkrpg'
    | '/api/announcement/nap'
  id:
    | '__root__'
    | '/'
    | '/announcement'
    | '/announcement/bh3'
    | '/announcement/hk4e'
    | '/announcement/hkrpg'
    | '/announcement/nap'
    | '/api/announcement/bh3'
    | '/api/announcement/hk4e'
    | '/api/announcement/hkrpg'
    | '/api/announcement/nap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementRoute: typeof AnnouncementRouteWithChildren
  ApiAnnouncementBh3Route: typeof ApiAnnouncementBh3Route
  ApiAnnouncementHk4eRoute: typeof ApiAnnouncementHk4eRoute
  ApiAnnouncementHkrpgRoute: typeof ApiAnnouncementHkrpgRoute
  ApiAnnouncementNapRoute: typeof ApiAnnouncementNapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement': {
      id: '/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof AnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/bh3': {
      id: '/announcement/bh3'
      path: '/bh3'
      fullPath: '/announcement/bh3'
      preLoaderRoute: typeof AnnouncementBh3RouteImport
      parentRoute: typeof AnnouncementRoute
    }
    '/announcement/hk4e': {
      id: '/announcement/hk4e'
      path: '/hk4e'
      fullPath: '/announcement/hk4e'
      preLoaderRoute: typeof AnnouncementHk4eRouteImport
      parentRoute: typeof AnnouncementRoute
    }
    '/announcement/hkrpg': {
      id: '/announcement/hkrpg'
      path: '/hkrpg'
      fullPath: '/announcement/hkrpg'
      preLoaderRoute: typeof AnnouncementHkrpgRouteImport
      parentRoute: typeof AnnouncementRoute
    }
    '/announcement/nap': {
      id: '/announcement/nap'
      path: '/nap'
      fullPath: '/announcement/nap'
      preLoaderRoute: typeof AnnouncementNapRouteImport
      parentRoute: typeof AnnouncementRoute
    }
    '/api/announcement/bh3': {
      id: '/api/announcement/bh3'
      path: '/api/announcement/bh3'
      fullPath: '/api/announcement/bh3'
      preLoaderRoute: typeof ApiAnnouncementBh3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcement/hk4e': {
      id: '/api/announcement/hk4e'
      path: '/api/announcement/hk4e'
      fullPath: '/api/announcement/hk4e'
      preLoaderRoute: typeof ApiAnnouncementHk4eRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcement/hkrpg': {
      id: '/api/announcement/hkrpg'
      path: '/api/announcement/hkrpg'
      fullPath: '/api/announcement/hkrpg'
      preLoaderRoute: typeof ApiAnnouncementHkrpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcement/nap': {
      id: '/api/announcement/nap'
      path: '/api/announcement/nap'
      fullPath: '/api/announcement/nap'
      preLoaderRoute: typeof ApiAnnouncementNapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnnouncementRouteChildren {
  AnnouncementBh3Route: typeof AnnouncementBh3Route
  AnnouncementHk4eRoute: typeof AnnouncementHk4eRoute
  AnnouncementHkrpgRoute: typeof AnnouncementHkrpgRoute
  AnnouncementNapRoute: typeof AnnouncementNapRoute
}

const AnnouncementRouteChildren: AnnouncementRouteChildren = {
  AnnouncementBh3Route: AnnouncementBh3Route,
  AnnouncementHk4eRoute: AnnouncementHk4eRoute,
  AnnouncementHkrpgRoute: AnnouncementHkrpgRoute,
  AnnouncementNapRoute: AnnouncementNapRoute,
}

const AnnouncementRouteWithChildren = AnnouncementRoute._addFileChildren(
  AnnouncementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementRoute: AnnouncementRouteWithChildren,
  ApiAnnouncementBh3Route: ApiAnnouncementBh3Route,
  ApiAnnouncementHk4eRoute: ApiAnnouncementHk4eRoute,
  ApiAnnouncementHkrpgRoute: ApiAnnouncementHkrpgRoute,
  ApiAnnouncementNapRoute: ApiAnnouncementNapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
