/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementRouteRouteImport } from './routes/announcement/route'
import { Route as AnnouncementBh3RouteRouteImport } from './routes/announcement/bh3/route'
import { Route as AnnouncementHk4eRouteRouteImport } from './routes/announcement/hk4e/route'
import { Route as AnnouncementHkrpgRouteRouteImport } from './routes/announcement/hkrpg/route'
import { Route as AnnouncementNapRouteRouteImport } from './routes/announcement/nap/route'
import { Route as ApiAnnouncementBh3RouteRouteImport } from './routes/api/announcement/bh3/route'
import { Route as ApiAnnouncementHk4eRouteRouteImport } from './routes/api/announcement/hk4e/route'
import { Route as ApiAnnouncementHkrpgRouteRouteImport } from './routes/api/announcement/hkrpg/route'
import { Route as ApiAnnouncementNapRouteRouteImport } from './routes/api/announcement/nap/route'
import { Route as ApiAnnouncementBh3OcrRouteImport } from './routes/api/announcement/bh3/ocr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementRouteRoute = AnnouncementRouteRouteImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementBh3RouteRoute = AnnouncementBh3RouteRouteImport.update({
  id: '/bh3',
  path: '/bh3',
  getParentRoute: () => AnnouncementRouteRoute,
} as any)
const AnnouncementHk4eRouteRoute = AnnouncementHk4eRouteRouteImport.update({
  id: '/hk4e',
  path: '/hk4e',
  getParentRoute: () => AnnouncementRouteRoute,
} as any)
const AnnouncementHkrpgRouteRoute = AnnouncementHkrpgRouteRouteImport.update({
  id: '/hkrpg',
  path: '/hkrpg',
  getParentRoute: () => AnnouncementRouteRoute,
} as any)
const AnnouncementNapRouteRoute = AnnouncementNapRouteRouteImport.update({
  id: '/nap',
  path: '/nap',
  getParentRoute: () => AnnouncementRouteRoute,
} as any)
const ApiAnnouncementBh3RouteRoute = ApiAnnouncementBh3RouteRouteImport.update({
  id: '/api/announcement/bh3',
  path: '/api/announcement/bh3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementHk4eRouteRoute =
  ApiAnnouncementHk4eRouteRouteImport.update({
    id: '/api/announcement/hk4e',
    path: '/api/announcement/hk4e',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnnouncementHkrpgRouteRoute =
  ApiAnnouncementHkrpgRouteRouteImport.update({
    id: '/api/announcement/hkrpg',
    path: '/api/announcement/hkrpg',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnnouncementNapRouteRoute = ApiAnnouncementNapRouteRouteImport.update({
  id: '/api/announcement/nap',
  path: '/api/announcement/nap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementBh3OcrRoute = ApiAnnouncementBh3OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => ApiAnnouncementBh3RouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteRouteWithChildren
  '/announcement/bh3': typeof AnnouncementBh3RouteRoute
  '/announcement/hk4e': typeof AnnouncementHk4eRouteRoute
  '/announcement/hkrpg': typeof AnnouncementHkrpgRouteRoute
  '/announcement/nap': typeof AnnouncementNapRouteRoute
  '/api/announcement/bh3': typeof ApiAnnouncementBh3RouteRouteWithChildren
  '/api/announcement/hk4e': typeof ApiAnnouncementHk4eRouteRoute
  '/api/announcement/hkrpg': typeof ApiAnnouncementHkrpgRouteRoute
  '/api/announcement/nap': typeof ApiAnnouncementNapRouteRoute
  '/api/announcement/bh3/ocr': typeof ApiAnnouncementBh3OcrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteRouteWithChildren
  '/announcement/bh3': typeof AnnouncementBh3RouteRoute
  '/announcement/hk4e': typeof AnnouncementHk4eRouteRoute
  '/announcement/hkrpg': typeof AnnouncementHkrpgRouteRoute
  '/announcement/nap': typeof AnnouncementNapRouteRoute
  '/api/announcement/bh3': typeof ApiAnnouncementBh3RouteRouteWithChildren
  '/api/announcement/hk4e': typeof ApiAnnouncementHk4eRouteRoute
  '/api/announcement/hkrpg': typeof ApiAnnouncementHkrpgRouteRoute
  '/api/announcement/nap': typeof ApiAnnouncementNapRouteRoute
  '/api/announcement/bh3/ocr': typeof ApiAnnouncementBh3OcrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcement': typeof AnnouncementRouteRouteWithChildren
  '/announcement/bh3': typeof AnnouncementBh3RouteRoute
  '/announcement/hk4e': typeof AnnouncementHk4eRouteRoute
  '/announcement/hkrpg': typeof AnnouncementHkrpgRouteRoute
  '/announcement/nap': typeof AnnouncementNapRouteRoute
  '/api/announcement/bh3': typeof ApiAnnouncementBh3RouteRouteWithChildren
  '/api/announcement/hk4e': typeof ApiAnnouncementHk4eRouteRoute
  '/api/announcement/hkrpg': typeof ApiAnnouncementHkrpgRouteRoute
  '/api/announcement/nap': typeof ApiAnnouncementNapRouteRoute
  '/api/announcement/bh3/ocr': typeof ApiAnnouncementBh3OcrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcement'
    | '/announcement/bh3'
    | '/announcement/hk4e'
    | '/announcement/hkrpg'
    | '/announcement/nap'
    | '/api/announcement/bh3'
    | '/api/announcement/hk4e'
    | '/api/announcement/hkrpg'
    | '/api/announcement/nap'
    | '/api/announcement/bh3/ocr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcement'
    | '/announcement/bh3'
    | '/announcement/hk4e'
    | '/announcement/hkrpg'
    | '/announcement/nap'
    | '/api/announcement/bh3'
    | '/api/announcement/hk4e'
    | '/api/announcement/hkrpg'
    | '/api/announcement/nap'
    | '/api/announcement/bh3/ocr'
  id:
    | '__root__'
    | '/'
    | '/announcement'
    | '/announcement/bh3'
    | '/announcement/hk4e'
    | '/announcement/hkrpg'
    | '/announcement/nap'
    | '/api/announcement/bh3'
    | '/api/announcement/hk4e'
    | '/api/announcement/hkrpg'
    | '/api/announcement/nap'
    | '/api/announcement/bh3/ocr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementRouteRoute: typeof AnnouncementRouteRouteWithChildren
  ApiAnnouncementBh3RouteRoute: typeof ApiAnnouncementBh3RouteRouteWithChildren
  ApiAnnouncementHk4eRouteRoute: typeof ApiAnnouncementHk4eRouteRoute
  ApiAnnouncementHkrpgRouteRoute: typeof ApiAnnouncementHkrpgRouteRoute
  ApiAnnouncementNapRouteRoute: typeof ApiAnnouncementNapRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement': {
      id: '/announcement'
      path: '/announcement'
      fullPath: '/announcement'
      preLoaderRoute: typeof AnnouncementRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcement/bh3': {
      id: '/announcement/bh3'
      path: '/bh3'
      fullPath: '/announcement/bh3'
      preLoaderRoute: typeof AnnouncementBh3RouteRouteImport
      parentRoute: typeof AnnouncementRouteRoute
    }
    '/announcement/hk4e': {
      id: '/announcement/hk4e'
      path: '/hk4e'
      fullPath: '/announcement/hk4e'
      preLoaderRoute: typeof AnnouncementHk4eRouteRouteImport
      parentRoute: typeof AnnouncementRouteRoute
    }
    '/announcement/hkrpg': {
      id: '/announcement/hkrpg'
      path: '/hkrpg'
      fullPath: '/announcement/hkrpg'
      preLoaderRoute: typeof AnnouncementHkrpgRouteRouteImport
      parentRoute: typeof AnnouncementRouteRoute
    }
    '/announcement/nap': {
      id: '/announcement/nap'
      path: '/nap'
      fullPath: '/announcement/nap'
      preLoaderRoute: typeof AnnouncementNapRouteRouteImport
      parentRoute: typeof AnnouncementRouteRoute
    }
    '/api/announcement/bh3': {
      id: '/api/announcement/bh3'
      path: '/api/announcement/bh3'
      fullPath: '/api/announcement/bh3'
      preLoaderRoute: typeof ApiAnnouncementBh3RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcement/hk4e': {
      id: '/api/announcement/hk4e'
      path: '/api/announcement/hk4e'
      fullPath: '/api/announcement/hk4e'
      preLoaderRoute: typeof ApiAnnouncementHk4eRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcement/hkrpg': {
      id: '/api/announcement/hkrpg'
      path: '/api/announcement/hkrpg'
      fullPath: '/api/announcement/hkrpg'
      preLoaderRoute: typeof ApiAnnouncementHkrpgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcement/nap': {
      id: '/api/announcement/nap'
      path: '/api/announcement/nap'
      fullPath: '/api/announcement/nap'
      preLoaderRoute: typeof ApiAnnouncementNapRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcement/bh3/ocr': {
      id: '/api/announcement/bh3/ocr'
      path: '/ocr'
      fullPath: '/api/announcement/bh3/ocr'
      preLoaderRoute: typeof ApiAnnouncementBh3OcrRouteImport
      parentRoute: typeof ApiAnnouncementBh3RouteRoute
    }
  }
}

interface AnnouncementRouteRouteChildren {
  AnnouncementBh3RouteRoute: typeof AnnouncementBh3RouteRoute
  AnnouncementHk4eRouteRoute: typeof AnnouncementHk4eRouteRoute
  AnnouncementHkrpgRouteRoute: typeof AnnouncementHkrpgRouteRoute
  AnnouncementNapRouteRoute: typeof AnnouncementNapRouteRoute
}

const AnnouncementRouteRouteChildren: AnnouncementRouteRouteChildren = {
  AnnouncementBh3RouteRoute: AnnouncementBh3RouteRoute,
  AnnouncementHk4eRouteRoute: AnnouncementHk4eRouteRoute,
  AnnouncementHkrpgRouteRoute: AnnouncementHkrpgRouteRoute,
  AnnouncementNapRouteRoute: AnnouncementNapRouteRoute,
}

const AnnouncementRouteRouteWithChildren =
  AnnouncementRouteRoute._addFileChildren(AnnouncementRouteRouteChildren)

interface ApiAnnouncementBh3RouteRouteChildren {
  ApiAnnouncementBh3OcrRoute: typeof ApiAnnouncementBh3OcrRoute
}

const ApiAnnouncementBh3RouteRouteChildren: ApiAnnouncementBh3RouteRouteChildren =
  {
    ApiAnnouncementBh3OcrRoute: ApiAnnouncementBh3OcrRoute,
  }

const ApiAnnouncementBh3RouteRouteWithChildren =
  ApiAnnouncementBh3RouteRoute._addFileChildren(
    ApiAnnouncementBh3RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementRouteRoute: AnnouncementRouteRouteWithChildren,
  ApiAnnouncementBh3RouteRoute: ApiAnnouncementBh3RouteRouteWithChildren,
  ApiAnnouncementHk4eRouteRoute: ApiAnnouncementHk4eRouteRoute,
  ApiAnnouncementHkrpgRouteRoute: ApiAnnouncementHkrpgRouteRoute,
  ApiAnnouncementNapRouteRoute: ApiAnnouncementNapRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
